#!/bin/sh

# a convenient replacement for reboot_detach

if [ -f /sbin/kexec ]; then
	if [ -f /do-kexec ]; then
		start-stop-daemon -S -x /usr/share/fakePXE/kexec.sh -b
	fi
fi

start-stop-daemon -S -x /sbin/reboot -b -- -f
